export const NATIVE_ALIGNMENTS: Record<string, { x: 'start' | 'center' | 'end', y: 'start' | 'center' | 'end' }> = {
  'header': { x: 'center', y: 'start' },
  'header-logo': { x: 'start', y: 'center' },
  'header-club': { x: 'center', y: 'center' },
  'header-collab': { x: 'end', y: 'center' },
  'header-extra': { x: 'start', y: 'center' },
  'header-extra2': { x: 'end', y: 'center' },
  'header-intro': { x: 'center', y: 'start' },
  'title': { x: 'center', y: 'center' },
  'title-text': { x: 'center', y: 'center' },
  'tagline': { x: 'center', y: 'center' },
  'tagline-text': { x: 'center', y: 'center' },
  'details': { x: 'center', y: 'center' },
  'details-date': { x: 'start', y: 'center' },
  'details-time': { x: 'start', y: 'center' },
  'details-venue': { x: 'start', y: 'start' },
  'details-fee': { x: 'start', y: 'start' },
  'tags': { x: 'center', y: 'center' },
  'tags-teamsize': { x: 'center', y: 'center' },
  'tags-prizepool': { x: 'center', y: 'center' },
  'footer': { x: 'center', y: 'end' },
  'footer-poc1': { x: 'start', y: 'end' },
  'footer-poc2': { x: 'end', y: 'end' },
  'footer-qrbox': { x: 'center', y: 'center' },
  'footer-qrscan': { x: 'end', y: 'center' },
};
